version: '3'
services:
  database:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=training
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
#    volumes:
#      - ./data/database:/var/lib/postgresql/data/application
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=training@sages.pl
      - PGADMIN_DEFAULT_PASSWORD=123
  batch:
    image: landrzejewski/batch
    ports:
      - 7000:9000
    environment:
      - SERVER_PORT=9000
      - DATABASE_URL=jdbc:postgresql://database:5432/training
